### ISSUE TITLE
UNKNOWN Games in Gallery

### ISSUE THREAD

**Issue by LostDragonist** [wabbajack-tools/wabbajack-tools.github.io#133]
Enderal and FO4VR show up as "UNKNOWN" in the gallery.

![image](https://user-images.githubusercontent.com/7862539/88764052-19817400-d129-11ea-8b0d-f2e8592c14d0.png)

**Comment by erri120** [comment]
Fixed in 1b4b8a48fc93c7cee0110093043a3ca4fecd86fe
