### ISSUE TITLE
Improve Archive Search to contain Mod Names as well

### ISSUE THREAD

**Issue by ixanza** [wabbajack-tools/wabbajack-tools.github.io#140]
**Is your feature request related to a problem? Please describe.**
It’s hard to find out which mod is included using archive search when zip names are pretty vague in their naming scheme

**Describe the solution you'd like**
To add on to archive name we should include the mod name as well for mods on nexus. Maybe LL too if possible

**Describe alternatives you've considered**
Modwatch

**Comment by erri120** [comment]
Done in d41a8f64bbda876b8fc35d4b59c83530a417f961 and b4297064e2ce5d6e0d77299c24cd7a441f5e93bf
