### ISSUE TITLE
[Feature request] Unified knowledge base / documentation source

### ISSUE THREAD

**Issue by spaghetti-guy** [wabbajack-tools/wabbajack-tools.github.io#298]
Until Discord implements a way to integrate a knowledge base or wiki into a Discord server, I think the Wabbajack community could benefit from a unified place for detailed documentation for common issues / solutions. The most immediate benefit to this is a single, reliable source for up-to-date information. This could be hosted on the main Wabbajack site or Wabajack Github page.

This could be integrated into the Wabbajack Discord server by modifying Carl's commands to also include a link for more detailed information, looking something like this: 
![feWgD](https://user-images.githubusercontent.com/9104303/110258873-57216780-7f6a-11eb-8b2c-d356838b6f19.png)

The page located at the bottom blue link's destination might include a step-by-step guide with pictures on how to complete this process. It could also include embedded (or links to) videos walking the user through this process. 

While Carl could help direct users to these pages, this knowledge base doesn't need to be restricted to information the bot already provides. For example, modlist authors could link to instructions for common setup tasks instead of using a readme template or copying information from other lists. Some examples might include disabling the Steam overlay or using LostDragonist's Steam Library tool to make sure a game isn't installed in Program Files.

Additionally, a specific page on this knowledge base that the community would benefit from is a FAQ for Wabbajack issues. 

### Deployment
Because I'm not sure people would actually look at these pages, it might be best to setup just 1 or 2 to supplement common Carl commands and see how they do. Bitly (or some alternative) links could be used to gather metrics on how many people are actually clicking the links for more information. 

### Benefits
- More detailed instructions might help those who don't "get it" from Carl's current responses alone
- Ability to provide significantly clearer and more detailed instructions
- Some setup instructions on modlists's readme pages could instead point to centralized documentation so that they are always kept up to date and do not differ (creates cohesion to the install experience)
- Mods, authors, and helpers spend less time typing out the same thing to different users

### Possible issues
- Would people actually visit these pages? Users already have trouble following instructions. They would need to know to check an external site for common issues. 
  - Could Carl help more than just including links at the bottom of his responses?)
- The pages should probably not be editable to the general public in order to prevent vandalism. This would require maintaining a separate list of people with edit access. 
  - Modlist authors and moderators+ are the obvious groups to allow, but possibly allowing Golden Saints and Aedra to some pages may be beneficial
- Requires people to actually write the documentation and then maintain it in case something is made obsolete
- Fragments the locations solutions reside in

**Comment by erri120** [comment]
Done in 9ea287edcb4b646535a5cd86c66fb7b3400fdd02
