### ISSUE TITLE
Modlist readme page caching issue.

### ISSUE THREAD

**Issue by Modulator-Mocker-Ellipse8** [wabbajack-tools/wabbajack-tools.github.io#33]
Issue:
When you open a modlist readme and then back out and open another one, it will display the readme information for the previously viewed modlist.
It will show the correct banner and brief description for the modlist, but the readme text will be incorrect.
Steps to reproduce:
1. Click View button for any modlist.
2. Press the back button in your browser.
3. Press the view button for any other modlist.

**Comment by erri120** [comment]
Fixed in 8989d4cd89013a9199993257d4c7fade460a4aa5
