### ISSUE TITLE
Table of Contents of README.md's on the website don't work

### ISSUE THREAD

**Issue by tr4wzified** [wabbajack-tools/wabbajack-tools.github.io#54]
**Describe the bug**
Clicking a Table of Contents link on the various modlists in the gallery on the website will result in you being redirected to the homepage instead of the id it's supposed to scroll down to.
Does this for both [TVO](https://www.wabbajack.org/modlists/gallery/tvo) and [Elder Souls](https://www.wabbajack.org/modlists/gallery/eldersouls).

If you click the Preamble in TVO for example, it will redirect to https://www.wabbajack.org/#preamble when it should redirect to https://www.wabbajack.org/modlists/gallery/tvo#preamble

**Comment by erri120** [comment]
Weird bug:
![07-06-2020 14-51-14](https://user-images.githubusercontent.com/16577545/83969119-9cbae200-a8bd-11ea-8c61-0a7221e05184.png)
(local test server)
![07-06-2020 14-51-21](https://user-images.githubusercontent.com/16577545/83969120-9f1d3c00-a8bd-11ea-9e51-95a0413729af.png)
(live version)

**Comment by erri120** [comment]
Fixed in 511f03ea5b36202f374b8918539f8deb42c5ec84
