### ISSUE TITLE
Exe link on the website

### ISSUE THREAD

**Issue by LivelyDismay** [wabbajack-tools/wabbajack-tools.github.io#63]
**Is your feature request related to a problem? Please describe.**
There is no clear link to the Wabbajack.exe on the website.

**Describe the solution you'd like**
Add https://github.com/wabbajack-tools/wabbajack/releases/download/2.0.9.0/Wabbajack.exe to the website.

**Describe alternatives you've considered**
N/A

**Additional context**
Would have to be updated with each new build, so we would just need to remember to do that.

**Comment by erri120** [comment]
Resolved in 6de24010f45238987275b63c56fbb4b36a4a678b
